assignment_loss_scale: 1.0
balance_classifications: false
balance_jets: 0
balance_losses: true
balance_particles: 1
batch_size: 1024
classification_loss_scale: 0.0
combinatorial_scale: 0.0
combine_pair_loss: min
dataset_limit: 1.0
dataset_randomization: 0
detection_loss_scale: 1.0
dropout: 0.1
epochs: 50
event_info_file: ./event_files/one-lepton-vbsvvh.yaml
focal_gamma: 0.0
gradient_clip: 0.0
hidden_dim: 64
initial_embedding_dim: 16
initial_embedding_skip_connections: 1
kl_loss_scale: 0.0
l2_penalty: 0.0002
learning_rate: 0.0001
learning_rate_cycles: 1
learning_rate_warmup_epochs: 1.0
limit_to_num_jets: 0
linear_activation: gelu
linear_block_type: GRU
linear_prelu_activation: true
mask_sequence_vectors: 1
masking: Filling
normalization: LayerNorm
normalize_features: 1
num_attention_heads: 4
num_branch_embedding_layers: 3
num_branch_encoder_layers: 3
num_classification_layers: 1
num_dataloader_workers: 16
num_detector_layers: 2
num_embedding_layers: 10
num_encoder_layers: 6
num_gpu: 1
num_jet_embedding_layers: 0
num_jet_encoder_layers: 2
num_regression_layers: 1
optimizer: AdamW
partial_events: 1
position_embedding_dim: 32
regression_loss_scale: 0.0
skip_connections: 1
split_symmetric_attention: 1
testing_file: ''
train_validation_split: 0.8
training_file: ./data/output.h5
transformer_activation: gelu
transformer_dim: 64
transformer_dim_scale: 2.0
transformer_type: Gated
trial_output_dir: ./test_output
trial_time: ''
usable_gpus: ''
validation_file: ''
verbose_output: false
